"""Plain-language action for each finding, chosen from a fixed table.

The table only restates what the deterministic rules already established. A drug name appears
in an action only when the rule's own suggestion carries it (a guideline regimen), and nothing
here is generated by a model.
"""

from pydantic import BaseModel

from .schemas import CultureStatus, Finding, Outcome, Specimen, SyndromeRule

_ACTIONS: dict[tuple[str, Outcome], str] = {
    (
        "R0_IDENTIFIED",
        Outcome.CANNOT_ASSESS,
    ): "Confirm the intended drug; no other check ran for it.",
    ("R1_INDICATION", Outcome.FLAG): "Review antibiotic selection against the NCDC guideline.",
    ("R1_INDICATION", Outcome.CANNOT_ASSESS): "Ask the prescriber to document the indication, "
    "or select the syndrome it matches, so the guideline check can run.",
    ("R2_AWARE", Outcome.FLAG): "Review whether a lower-tier (Access) antibiotic can be used, "
    "or obtain stewardship approval for Reserve drugs.",
    ("R2_AWARE", Outcome.CANNOT_ASSESS): "Check the WHO AWaRe tier manually.",
    ("R3_DOSE", Outcome.FLAG): "Review dose before administration against the guideline range.",
    ("R4_RENAL", Outcome.FLAG): "Review dose or drug choice for the patient's kidney function.",
    ("R4_RENAL", Outcome.CANNOT_ASSESS): "Provide age, weight and serum creatinine so renal "
    "dosing can be checked, or check it manually.",
    ("R5_DURATION", Outcome.FLAG): "Review the planned duration against the guideline.",
    ("R6_ALLERGY", Outcome.FLAG): "Review the documented allergy before administration.",
    ("R6_ALLERGY", Outcome.CANNOT_ASSESS): "Document the patient's allergy status.",
    ("R7_PREGNANCY", Outcome.FLAG): "Avoid this drug in pregnancy unless no alternative exists.",
    ("R7_PREGNANCY", Outcome.CANNOT_ASSESS): "Record whether the patient is pregnant.",
    ("R8_DRUG_DISEASE", Outcome.FLAG): "Review the quoted label caution against the patient's "
    "condition before administration.",
    ("R9_IV_TO_ORAL", Outcome.FLAG): "Confirm the patient is clinically stable and can take oral "
    "medication, then consider the guideline oral option.",
    ("C1_CULTURE_BEFORE_WATCH", Outcome.FLAG): "Obtain a culture if not already sent.",
    ("C3_BUG_DRUG_MISMATCH", Outcome.FLAG): "Review antibiotic selection and consider an "
    "alternative the organism is susceptible to.",
    ("C4_DE_ESCALATE", Outcome.FLAG): "Consider stepping down if the patient is clinically stable.",
    ("C5_NO_GROWTH", Outcome.FLAG): "Clinician to decide whether antibiotics are still needed.",
    ("C6_CONTAMINANT", Outcome.FLAG): "Confirm the isolate is a contaminant and consider "
    "repeating the culture.",
    ("C7_INTERMEDIATE", Outcome.FLAG): "Review the antibiotic; an intermediate result is not "
    "treated as susceptible.",
    ("C8_NOT_TESTED", Outcome.CANNOT_ASSESS): "Ask the laboratory whether this antibiotic was "
    "tested.",
    ("C9_ORGANISM_UNKNOWN", Outcome.CANNOT_ASSESS): "Record the organism's full scientific name.",
    ("DDI_INTERACTION", Outcome.FLAG): "Review the reported interaction with the pharmacist "
    "before the drugs are co-administered.",
    ("DDI_CANNOT_ASSESS", Outcome.CANNOT_ASSESS): "Confirm the drug identity, or review the "
    "drug's interactions manually; DrugBank could not answer this pair.",
}


def action_for(finding: Finding) -> str | None:
    """What the clinician should do about a finding; None for a pass."""
    if finding.outcome is Outcome.PASS:
        return None
    # DDI rule ids carry the pair after a colon ("DDI_INTERACTION:amoxicillin+clarithromycin");
    # the action table is keyed by the rule family.
    text = _ACTIONS.get((finding.rule_id.split(":", 1)[0], finding.outcome))
    if text is None and finding.outcome is Outcome.CANNOT_ASSESS and finding.missing_inputs:
        text = "Supply the missing input (" + ", ".join(finding.missing_inputs) + ")."
    elif text is None and finding.rule_id in ("R3_DOSE", "R5_DURATION"):
        text = (
            "The guideline gives no matching dose/duration for this drug, syndrome and route; "
            "check it manually."
        )
    if text is None:
        text = (
            "Review this finding."
            if finding.outcome is Outcome.FLAG
            else "Supply the missing input or check manually."
        )
    suggestion = finding.suggestion
    if suggestion is not None and suggestion.drug and suggestion.action in ("switch",):
        text += f" Guideline option: {suggestion.drug}."
    return text


class CultureSummary(BaseModel):
    """Where the episode stands on cultures, stated so 'no culture' is never read as 'clean'."""

    state: str  # NOT_AVAILABLE | PENDING | NO_GROWTH | GROWTH_NO_AST | FINAL | CONTAMINATED
    message: str
    action: str | None = None


def culture_summary(
    specimens: tuple[Specimen, ...], syndrome: SyndromeRule | None
) -> CultureSummary:
    """Summarise culture availability. No specimen (or only NOT_SENT) is NOT_AVAILABLE, which
    means unknown: it is not a negative culture and implies nothing about resistance."""
    sent = [s for s in specimens if s.status is not CultureStatus.NOT_SENT]
    if not sent:
        required = syndrome is not None and syndrome.culture_required
        return CultureSummary(
            state="NOT_AVAILABLE",
            message="Culture result unavailable. Susceptibility is unknown, not assumed.",
            action="Obtain a culture; the applicable guideline asks for one before antibiotics."
            if required
            else "Obtain/review culture if required by the applicable guideline.",
        )
    if any(s.status is CultureStatus.FINAL for s in sent):
        return CultureSummary(state="FINAL", message="Final culture with isolate(s) is available.")
    states = {s.status for s in sent}
    for status, message, action in (
        (
            CultureStatus.GROWTH_NO_AST,
            "Culture shows growth but susceptibility testing is not available.",
            "Follow up the susceptibility report.",
        ),
        (
            CultureStatus.PENDING,
            "Culture result is pending.",
            "Review again when the culture is reported.",
        ),
        (
            CultureStatus.NO_GROWTH,
            "Culture shows no growth (negative).",
            "Clinician to review whether antibiotics are still needed.",
        ),
        (CultureStatus.CONTAMINATED, "Culture is contaminated.", "Consider repeating the culture."),
    ):
        if status in states:
            return CultureSummary(state=status.value, message=message, action=action)
    return CultureSummary(state="NOT_AVAILABLE", message="Culture result unavailable.")
