#!/usr/bin/env python3
"""Build backend/stewardship/rulepack/syndromes_ncdc.yaml and docs/NCDC_IMPORT_REPORT.md.

Reads the NCDC 2025 dataset (data/reference/ncdc/syndromes_ncdc_2025.yaml) and the manifest
(backend/stewardship/rulepack/ncdc_import.yaml), converts the regimens the manifest names into
rule-pack rows, and writes a report of every dataset row that was not imported, every number that
was not carried over, and every difference from the hand-checked rule pack.

Usage: python scripts/import_ncdc.py [--check]
  --check  exit 1 if the generated files are out of date instead of writing them
"""

import sys
from collections import Counter
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from backend.stewardship import config  # noqa: E402
from backend.stewardship.drugs import Catalog  # noqa: E402
from backend.stewardship.ncdc_import import ImportResult, convert, load_yaml  # noqa: E402

REPORT_MD = config.REPO_ROOT / "docs" / "NCDC_IMPORT_REPORT.md"

HEADER = """\
# GENERATED by scripts/import_ncdc.py from data/reference/ncdc/syndromes_ncdc_2025.yaml and
# rulepack/ncdc_import.yaml. Do not edit by hand: change the manifest and re-run the script.
#
# Same format as syndromes.yaml. route_basis "dataset" = the route as recorded in the NCDC
# dataset. A null daily_dose_mg or duration_days means the dataset value does not convert exactly
# (see docs/NCDC_IMPORT_REPORT.md), so R3/R5 return CANNOT_ASSESS for it.

"""


def build() -> ImportResult:
    return convert(
        load_yaml(config.NCDC_DATASET_YAML),
        load_yaml(config.NCDC_MANIFEST_YAML),
        load_yaml(config.SYNDROMES_YAML),
        Catalog.load(),
    )


def render_yaml(result: ImportResult) -> str:
    sources = load_yaml(config.SYNDROMES_YAML)["sources"]
    body = yaml.safe_dump(
        {"sources": sources, "syndromes": result.syndromes},
        sort_keys=False,
        width=100,
        allow_unicode=True,
        default_flow_style=None,
    )
    return HEADER + body


def _table(head: str, rows: list[tuple]) -> list[str]:
    cols = head.count("|") - 1
    out = [head, "|" + "---|" * cols]
    out += ["| " + " | ".join(str(c).replace("|", "/") for c in row) + " |" for row in rows]
    return out + [""]


def render_report(result: ImportResult) -> str:
    regimens = [r for s in result.syndromes for r in s["regimens"]]
    lines = [
        "# NCDC dataset import report",
        "",
        "Generated by `scripts/import_ncdc.py`. Do not edit by hand.",
        "",
        "Source: `data/reference/ncdc/syndromes_ncdc_2025.yaml` (NCDC/ICMR National Treatment "
        "Guidelines for Antimicrobial Use in Infectious Disease Syndromes v2.0, November 2025, "
        "machine-readable conversion from branch `complete-verification-incomplete`, commit "
        "173e92c). Grouping into syndrome codes: `backend/stewardship/rulepack/ncdc_import.yaml`.",
        "",
        "## Summary",
        "",
        f"- Imported syndrome codes: {len(result.syndromes)} "
        f"({sum(not s['antibiotics_indicated'] for s in result.syndromes)} no-antibiotic)",
        f"- Imported drug/route rows: {len(regimens)}; with a checkable daily dose: "
        f"{sum(r['daily_dose_mg'] is not None for r in regimens)}; with a checkable duration: "
        f"{sum(r['duration_days'] is not None for r in regimens)}",
        f"- Hand-checked codes compared with the dataset: {len(result.compared)}; "
        f"differences: {len(result.conflicts)} (the hand-checked row is kept in every case)",
        f"- Agents skipped: {len(result.skipped_agents)}; numbers not carried over: "
        f"{len(result.withheld)}; same drug and route merged with differing values: "
        f"{len(result.merged)}",
        f"- Dataset rows not imported: {len(result.unassigned)}",
        "",
        "## Imported syndrome codes",
        "",
    ]
    lines += _table(
        "| Code | NCDC section | Antibiotic indicated | Culture before antibiotics | Rows | "
        "Dose checkable | Duration checkable |",
        [
            (
                f"`{s['code']}`",
                f"{s['source']['section']}, p. {s['source']['page']}",
                "yes" if s["antibiotics_indicated"] else "no",
                "yes" if s["culture_required"] else "no",
                len(s["regimens"]),
                sum(r["daily_dose_mg"] is not None for r in s["regimens"]),
                sum(r["duration_days"] is not None for r in s["regimens"]),
            )
            for s in result.syndromes
        ],
    )
    lines += [
        "## Differences from the hand-checked rule pack",
        "",
        "Each hand-checked code in `rulepack/syndromes.yaml` was converted from the dataset the "
        "same way and compared row by row. The hand-checked row wins; the dataset row is not "
        "imported. `listed` = whether each side has the drug/route at all.",
        "",
        f"Compared: {', '.join(f'`{c}`' for c in result.compared)}.",
        "",
    ]
    lines += _table(
        "| Code | Drug | Route | Field | Hand-checked | Dataset |",
        [
            (f"`{c.code}`", c.generic, c.route, c.field, c.hand_checked, c.dataset)
            for c in result.conflicts
        ],
    )
    lines += ["## Agents skipped", ""]
    lines += _table(
        "| Dataset row | Drug | Reason |",
        [(n.ref, n.drug, n.reason) for n in result.skipped_agents],
    )
    lines += [
        "## Numbers not carried over",
        "",
        "The drug is imported (R1 sees it) but this dose or duration is not, so R3 or R5 returns "
        "CANNOT_ASSESS for it.",
        "",
    ]
    reasons = Counter(n.reason.split(":")[0] for n in result.withheld)
    lines += _table("| Reason | Count |", sorted(reasons.items(), key=lambda kv: -kv[1]))
    lines += _table(
        "| Dataset row | Drug | Reason |", [(n.ref, n.drug, n.reason) for n in result.withheld]
    )
    lines += ["## Same drug and route listed more than once", ""]
    lines += _table(
        "| Section | Drug | Detail |", [(n.ref, n.drug, n.reason) for n in result.merged]
    )
    lines += ["## Dataset rows not imported", ""]
    lines += _table(
        "| Dataset row | Drugs | Reason |",
        [(n.ref, n.drug or "-", n.reason) for n in result.unassigned],
    )
    return "\n".join(lines)


def main() -> int:
    result = build()
    outputs = {
        config.NCDC_SYNDROMES_YAML: render_yaml(result),
        REPORT_MD: render_report(result),
    }
    if "--check" in sys.argv:
        stale = [p for p, text in outputs.items() if not p.exists() or p.read_text() != text]
        for path in stale:
            print(f"out of date: {path.relative_to(config.REPO_ROOT)}")
        return 1 if stale else 0
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(config.REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
